### ISSUE TITLE
Error At my first use

### ISSUE THREAD

**Issue by sebadiaz** [xxhomey19/nba-go#25]
I did 

sudo npm install -g nba-go
nba-go game -T
/usr/local/lib/node_modules/nba-go/node_modules/nba/src/team-info.js:28
  ]).then(function ([teamStats, teamYears]) {
                    ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nba-go/node_modules/nba/src/index.js:1:84)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by sebadiaz** [comment]
WARN engine nba-go@0.1.9: wanted: {"node":">=6.0.0"} (current: {"node":"4.7.2","npm":"3.5.2"})

**Comment by xxhomey19** [comment]
Hi @sebadiaz ,
Upgrade your node version above v6.0.0 . This should work.

**Comment by insanity54** [comment]
I saw this issue as well. `nvm install v8.9.1 && nvm use v8.9.1 && !!`

**Comment by xxhomey19** [comment]
Hi all,
If you are still unable to install it, ping me and reopen this issue.
