### ISSUE TITLE
Unexpected Token Error issues upon running any command in terminal

### ISSUE THREAD

**Issue by mkayen** [xxhomey19/nba-go#41]
Running any command issues an Unexpected token error. I have not touched the code at all, I have only installed the code via npm.Thoughts on how to resolve?

nba-go game -d 2017/11/12

/usr/local/lib/node_modules/nba-go/node_modules/nba/src/team-info.js:28
  ]).then(function ([teamStats, teamYears]) {
                    ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nba-go/node_modules/nba/src/index.js:1:84)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)'

**Comment by xxhomey19** [comment]
What is your node version?

**Comment by mkayen** [comment]
4.2.6

**Comment by xxhomey19** [comment]
Upgrade it over 6.0.0, this issued should be solved.

**Comment by mkayen** [comment]
Worked! Thank you!
