### ISSUE TITLE
RequestError LOG

### ISSUE THREAD

**Issue by jessie-zly** [xxhomey19/nba-go#57]
## Firstly, I'm in China, and already install nba-go.
But when I ` NODE_ENV=development node bin/cli.js game -y` , response like this:

```
{ RequestError: Error: connect ETIMEDOUT 23.38.160.110:80
    at new RequestError (E:\nba-go\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\nba-go\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\nba-go\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\nba-go\node_modules\request\request.js:186:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (E:\nba-go\node_modules\request\request.js:878:8)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:385:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at Request.plumbing.init (E:\nba-go\node_modules\request-promise-core\lib\plumbing.js:36:28)
    at Request.RP$initInterceptor [as init] (E:\nba-go\node_modules\request-promise-core\configure\request2.js:41:2
7)
    at new Request (E:\nba-go\node_modules\request\request.js:128:8)
    at request (E:\nba-go\node_modules\request\index.js:53:10)
    at Function.fetch (E:\nba-go\node_modules\nba-stats-client\build\NbaStatsClient.js:55:43)
    at Object.getPlayByPlayFromDate (E:\nba-go\node_modules\nba-stats-client\build\NbaStatsClient.js:149:29)
    at Object.<anonymous> (E:/nba-go/src/command/game/index.js:225:25)
    at Generator.next (<anonymous>)
```

network problem?

**Comment by xxhomey19** [comment]
Hi @jessie-zly,
`ETIMEDOUT` means your request is timing out because server is not responding.
It looks similar to #8 . Are you behind proxy?

**Comment by jessie-zly** [comment]
ok now, just because of the network
