### ISSUE TITLE
"UnhandledPromiseRejectionWarning" in git bash

### ISSUE THREAD

**Issue by fralonra** [xxhomey19/nba-go#79]
When I ran `nba-go g` in a git bash tool on WIN10, the following error occurred:
```
(node:21280) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'width' of undefined
    at Object.render (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\cfonts\index.js:464:121)
    at Object.say (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\cfonts\index.js:536:23)
    at cfontsDate (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\lib\cli.js:2:41326)
    at C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\ramda\src\internal\_pipe.js:3:14
    at C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\ramda\src\internal\_arity.js:10:19
    at C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\lib\cli.js:2:21374
    at tryCatch (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\core-js\library\modules\_export.js:36:28)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
    at Object.I [as game] (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\lib\cli.js:2:24827)
    at Command.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\lib\cli.js:2:6890)
    at Command.listener (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\commander\index.js:654:12)
    at Command.parse (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\nba-go\lib\cli.js:2:7875)
(node:21280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It seems that the `window-size` package is undefined.
The error didn't come up when using other CLI tool, like PowerShell and VSCode.

I'm using:
```
Win10 64
node v8.11.1
npm v5.6.0
nba-go v0.4.0
```

**Comment by ericpardee** [comment]
Same here:

epardee@nhan7: ~$ nba-go game
```
⠇ Loading Game Schedule(node:39754) UnhandledPromiseRejectionWarning: FetchError: request to https://stats.nba.com/stats/teaminfocommon?LeagueID=00&Season=2017-18&SeasonType=Regular%20Season&TeamID=1610612761 failed, reason: read ETIMEDOUT
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/nba-go/node_modules/node-fetch/lib/index.js:1345:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:39754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39754) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Loading Game Schedule^C

macOS 10.14
node v10.12.0
npm 6.4.1
NBA GO version: 0.4.0

**Comment by njomb** [comment]
Same deal here:

njombwe@NJOMBWE-M-G1AS:~/Downloads/nba-go-master$ ./run.sh



 ██████╗   ██████╗   ██╗  █████╗      ██╗  ██╗  ██████╗      ██╗ ██████╗  ███████╗
 ╚════██╗ ██╔═████╗ ███║ ██╔══██╗    ██╔╝ ███║ ██╔═████╗    ██╔╝ ╚════██╗ ██╔════╝
  █████╔╝ ██║██╔██║ ╚██║ ╚█████╔╝   ██╔╝  ╚██║ ██║██╔██║   ██╔╝   █████╔╝ ███████╗
 ██╔═══╝  ████╔╝██║  ██║ ██╔══██╗  ██╔╝    ██║ ████╔╝██║  ██╔╝   ██╔═══╝  ╚════██║
 ███████╗ ╚██████╔╝  ██║ ╚█████╔╝ ██╔╝     ██║ ╚██████╔╝ ██╔╝    ███████╗ ███████║
 ╚══════╝  ╚═════╝   ╚═╝  ╚════╝  ╚═╝      ╚═╝  ╚═════╝  ╚═╝     ╚══════╝ ╚══════╝


⠹ Loading Game Schedule(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to https://stats.nba.com/stats/teaminfocommon?LeagueID=00&Season=2017-18&SeasonType=Regular%20Season&TeamID=1610612762 failed, reason: socket hang up
(node:1) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠇ Loading Game Schedule

macOS 10.14
node v8.9.1
npm 5.5.1
NBA Go Version 0.4.0

**Comment by qorrect** [comment]
stats.nba.com not coming back from the command line, if you paste that into a browser you'll notice it does return data.  Might have to mess with the headers to trick nba.com into thinking its a desktop request

**Comment by NotNate** [comment]
This issue happens with me too. Same error.

**Comment by machiiine** [comment]
I was able to resolve it by adding two headers getHeaders() method from the NbaStatsClient.js lib

'Connection': 'keep-alive'
'Accept-Language': 'en-US'

**Comment by qorrect** [comment]
Adding these headers worked for me too : 

`		 'Connection': 'keep-alive',
		 'Accept-Language': 'en-US'`

in NbaStatsClient.js in the nba-stats-client package, probably need to let them know.

**Comment by simonkeng** [comment]
Also having this issue: 

`nba-go g`

```
⠋ Loading Game Schedule(node:51577) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to https://stats.nba.com/stats/teaminfocommon?LeagueID=00&Season=2018-19&SeasonType=Regular%20Season&TeamID=1610612755 failed, reason: read ETIMEDOUT
(node:51577) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠦ Loading Game Schedule
```
I'm using macOS High Sierra 10.13.4 17E202 x86_64 with iTerm2. @qorrect, I made the edit you recommended, but it didn't seem to work for me (although I'm not a regular npm user or node developer, so it's probably my lack of knowledge). I ran `npm run build` in `nba-go/` but got this error: 

```
$ npm run build

> nba-go@0.4.0 build /usr/local/lib/node_modules/nba-go
> npm run clean && webpack --config webpack.config.js -p


> nba-go@0.4.0 clean /usr/local/lib/node_modules/nba-go
> rimraf lib packed

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/nba-go/webpack.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at requireConfig (/usr/local/lib/node_modules/nba-go/node_modules/webpack/bin/convert-argv.js:97:18)
    at /usr/local/lib/node_modules/nba-go/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/nba-go/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/usr/local/lib/node_modules/nba-go/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/usr/local/lib/node_modules/nba-go/node_modules/yargs/yargs.js:533:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nba-go@0.4.0 build: `npm run clean && webpack --config webpack.config.js -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nba-go@0.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Any help is much appreciated, I LOVE this project, thank you devs!

**Comment by qorrect** [comment]
@simonkeng this is how im building

- Clone the repository to ~/nba-go
- in ~/nba-go run : `npm install `
- Now youd have to edit that dependency in node_modules/nba-stats-client , this needs to be fixed in that lib properly to work
- run `npm run build`
- now the build is in lib/cli.js , run with `node lib/cli.js g -y`

**Comment by simonkeng** [comment]
Hi @qorrect, thanks so much for showing me the steps you took! I went through it and everything appeared to run properly, but mine is still hanging at `Loading Game Schedule`

Below is the edited code block I made in `/nba-go/node_modules/nba-stats-client/build/NbaStatsClient.js`

```javascript
    key: 'getHeaders',
    value: function getHeaders() {
      return { 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36',
        'referer': 'http://stats.nba.com/scores/', 'Connection': 'keep-alive', 'Accept-Language': 'en-US' };
    }
```

`cd` back up to `nba-go/` and run:

```
 npm run build

> nba-go@0.4.0 build /Users/keng/playground/nba/nba-go
> npm run clean && webpack --config webpack.config.js -p


> nba-go@0.4.0 clean /Users/keng/playground/nba/nba-go
> rimraf lib packed

Hash: db871b6d432993d56dfc
Version: webpack 3.12.0
Time: 2871ms
              Asset     Size  Chunks                    Chunk Names
             cli.js  47.2 kB       0  [emitted]         cli
         cli.js.map   187 kB       0  [emitted]         cli
fonts/ter-u12b.json   263 kB          [emitted]  [big]
fonts/ter-u12n.json   263 kB          [emitted]  [big]
   [0] ./src/utils/log.js 1.77 kB {0} [built]
  [13] ./src/command/game/network.js 1.02 kB {0} [built]
  [18] ./src/utils/catchAPIError.js 472 bytes {0} [built]
  [20] ./src/cli.js 6.12 kB {0} [built]
  [25] ./src/command/index.js 409 bytes {0} [built]
  [26] ./src/command/player/index.js 10.6 kB {0} [built]
  [27] ./src/command/player/info.js 2.69 kB {0} [built]
  [29] ./src/command/player/seasonStats.js 3.81 kB {0} [built]
  [30] ./src/command/player/infoCompare.js 3.27 kB {0} [built]
  [35] ./src/command/game/index.js 16.9 kB {0} [built]
  [52] ./src/command/game/boxScore.js 5.16 kB {0} [built]
  [54] ./src/command/game/live.js 6.52 kB {0} [built]
  [55] ./src/utils/cfonts.js 626 bytes {0} [built]
  [57] ./src/utils/blessed.js 5.25 kB {0} [built]
  [60] ./package.json 2.74 kB {0} [built]
    + 47 hidden modules
```
Then
```
 node lib/cli.js g -y                                                                                               4968ms



 ██████╗   ██████╗   ██╗  █████╗      ██╗  ██████╗   ██╗     ██╗  ██╗  ██╗
 ╚════██╗ ██╔═████╗ ███║ ██╔══██╗    ██╔╝ ██╔═████╗ ███║    ██╔╝ ███║ ███║
  █████╔╝ ██║██╔██║ ╚██║ ╚██████║   ██╔╝  ██║██╔██║ ╚██║   ██╔╝  ╚██║ ╚██║
 ██╔═══╝  ████╔╝██║  ██║  ╚═══██║  ██╔╝   ████╔╝██║  ██║  ██╔╝    ██║  ██║
 ███████╗ ╚██████╔╝  ██║  █████╔╝ ██╔╝    ╚██████╔╝  ██║ ██╔╝     ██║  ██║
 ╚══════╝  ╚═════╝   ╚═╝  ╚════╝  ╚═╝      ╚═════╝   ╚═╝ ╚═╝      ╚═╝  ╚═╝


⠙ Loading Game Schedule
```
..and its hanging here. 

The only difference is that I didn't clone the repo into `~` like you did, mine is in a subdirectory. I don't think this should make a difference though.

**Comment by simonkeng** [comment]
Okay, very confusing... It was working at the coffee shop, but now back home: 

```
$ node lib/cli.js g -y



 ██████╗   ██████╗   ██╗  █████╗      ██╗  ██████╗   ██╗     ██╗  ██╗  ██╗
 ╚════██╗ ██╔═████╗ ███║ ██╔══██╗    ██╔╝ ██╔═████╗ ███║    ██╔╝ ███║ ███║
  █████╔╝ ██║██╔██║ ╚██║ ╚██████║   ██╔╝  ██║██╔██║ ╚██║   ██╔╝  ╚██║ ╚██║
 ██╔═══╝  ████╔╝██║  ██║  ╚═══██║  ██╔╝   ████╔╝██║  ██║  ██╔╝    ██║  ██║
 ███████╗ ╚██████╔╝  ██║  █████╔╝ ██╔╝    ╚██████╔╝  ██║ ██╔╝     ██║  ██║
 ╚══════╝  ╚═════╝   ╚═╝  ╚════╝  ╚═╝      ╚═════╝   ╚═╝ ╚═╝      ╚═╝  ╚═╝


⠹ Loading Game Schedule(node:65875) UnhandledPromiseRejectionWarning: FetchError: request to https://stats.nba.com/stats/teaminfocommon?LeagueID=00&Season=2018-19&SeasonType=Regular%20Season&TeamID=1610612755 failed, reason: read ETIMEDOUT
    at ClientRequest.<anonymous> (/Users/keng/playground/nba/nba-go/node_modules/node-fetch/lib/index.js:1345:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:65875) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:65875) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠹ Loading Game Schedule
```

**Comment by saeranv** [comment]
I'm having this problem as well. I'm trying to solve it with @qorrect's method, however it's failing at the npm install step, with the following message:

```
1016 silly lockFile 4fd6d666-blessed-0-1-81 blessed@^0.1.81
1017 silly lockFile 4fd6d666-blessed-0-1-81 blessed@^0.1.81
1018 error Error: CERT_UNTRUSTED
1018 error     at SecurePair.<anonymous> (tls.js:1370:32)
1018 error     at SecurePair.EventEmitter.emit (events.js:92:17)
1018 error     at SecurePair.maybeInitFinished (tls.js:982:10)
1018 error     at CleartextStream.read [as _read] (tls.js:469:13)
1018 error     at CleartextStream.Readable.read (_stream_readable.js:320:10)
1018 error     at EncryptedStream.write [as _write] (tls.js:366:25)
1018 error     at doWrite (_stream_writable.js:223:10)
1018 error     at writeOrBuffer (_stream_writable.js:213:5)
1018 error     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
1018 error     at write (_stream_readable.js:583:24)
1018 error     at flow (_stream_readable.js:592:7)
1018 error     at Socket.pipeOnReadable (_stream_readable.js:624:5)
1019 error If you need help, you may report this log at:
1019 error     <http://github.com/isaacs/npm/issues>
1019 error or email it to:
1019 error     <npm-@googlegroups.com>
1020 error System Linux 4.9.125-linuxkit
1021 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
1022 error cwd /app/nba-go
1023 error node -v v0.10.25
1024 error npm -v 1.3.10
1025 verbose exit [ 1, true ]
```

Any ideas what could be wrong? 

S

**Comment by qorrect** [comment]
This is actually unrelated to the problem, its a build issue with NPM, googling on it seems to have found https://stackoverflow.com/questions/21855035/ssl-error-cert-untrusted-while-using-npm-command

**Comment by saeranv** [comment]
Okay, so having successfully followed @qorrect's instructions, now I'm running into this error when running `node lib/cli.js g -y`:
```
⠸ Loading Game Schedule...(4/6)

FetchError: request to https://stats.nba.com/stats/teaminfocommon?LeagueID=00&Season=2018-19&SeasonType=Regular%20Season&TeamID=1610612766 failed, reason: socket hang up

Oops, NBA.teamInfoCommon() goes wrong.
Please run nba-go again.
If it still does not work, feel free to open an issue on https://github.com/xxhomey19/nba-go/issues
```

I've run it twice and I'm getting the same message.
